id: {{deploymentId}}
metadata:
  name: ctt-sample-app-b
  namespace: margo-ctt
  deviceId: {{deviceId}}
spec:
  applicationId: ctt-sample-app-b
  deploymentProfile:
    type: compose
    components:
      - name: sample-app-b
        properties:
          repository: oci://registry.example.com/margo-ctt/sample-app-b
          revision: 1.0.0
          wait: true
